# Example configuration for testing a stdio MCP server
server:
  transport: stdio
  host: "npx -y @modelcontextprotocol/server-everything"  # Command to run the server

test:
  tool_name: echo
  tool_args:
    message: "Hello"
  concurrent_requests: 3
  duration_seconds: 15